export const projects = [
  {
    title: 'Bonvola App',
    description: "Este projeto trata-se da criação de uma aplicação mobile, onde o aplicativo irá excercer algumas funções básicas, como o login e cadastro do usuário, visualizar postagens de Instituições de Caridade, doar para essas instituiçoes, ter acesso ao Marketplace de Empresas parceiras, entre outros.",
      image: '/images/Bonvola App.png',
      tags: ['Flutter', 'Firebase'],
    source: 'https://drive.google.com/drive/folders/1-xwtgetuXoM6w2dhCHVH0jwDeTKGiXsp?usp=sharing',
    visit: 'https://github.com/JorgeHenrys',
    id: 0,
  },
  {
    title: 'Bonvola Admin',
    description:"Essa é uma aplicação web, que administra o sistema Bonvola, podendo ser acessada pelas Empresas Parceiras ou pelas Instituiçoes.",
    image: '/images/Bonvola Web.png',
    tags: ['Bootstrap', 'Firebase', 'JavaScript', 'Html', 'Css'],
    source: 'https://drive.google.com/drive/folders/1cDDrKbv8b4VEvSQnoymPKvipF0dpCzB5?usp=sharing',
    visit: 'https://github.com/JorgeHenrys',
    id: 1,
  },
  {
    title: 'Mundo Delivery App',
    description: "O projeto se trata da criação de um Marketplace, onde usúarios podem comprar produtos online.",
      image: '/images/Mundo Delivery App.png',
      tags: ['Flutter'],
    source: 'https://drive.google.com/drive/folders/1LDlZCQhNOj9bd2rNwazO5HhjSz_cJmyZ?usp=sharing',
    visit: 'https://github.com/JorgeHenrys',
    id: 2,
  },
  {
    title: 'Mundo Delivery Admin',
    description: "Sistema de Admin para as lanchonetes e/ou restaurantes cadastrar produtos e receber pedidos.",
    image: '/images/Mundo Delivery Web.png',
    tags: ['React', 'Node'],
    source: 'https://drive.google.com/drive/folders/1RdqyDDfTk7NtoLQ8fYW0HnK-DMmMC0LZ?usp=sharing',
    visit: 'https://github.com/JorgeHenrys',
    id: 3,
  },
  {
    title: 'Mais Robotic Quiz',
    description: "Aplicativo Mobile feito para auxiliar no aprendizado de robótica de crianças e adolescentes, onde ao final de cada modúlo de aula, há um quiz gamificado.",
    image: '/images/Mais Robotic Quiz.png',
    tags: ['Android Studio', 'Java'],
    source: 'https://drive.google.com/drive/folders/1G5p54UMUeK-tnojX4uZ55nWpbM36EM5u?usp=sharing',
    visit: 'https://github.com/JorgeHenrys',
    id: 4,
  },
  {
    title: 'Imobiliaria Sacoã',
    description: "Este aplicativo é feito para que usuários possam acessar e buscar empreendimentos e imóveis em determinadas regiões filtradas dentro do próprio app.",
    image: '/images/Imobiliaria Sacoa.png',
    tags: ['Flutter', 'Firebase'],
    source: 'https://drive.google.com/drive/folders/1O1LKwDzDzDbEE-s0o0_yvGqdYZoCQixV?usp=sharing',
    visit: 'https://github.com/JorgeHenrys',
    id: 5,
  },
  {
    title: 'Nativo App',
    description: "É um aplicativo desenvolvido para uma empresa de gerenciamento de sistemas de comércio, onde o app auxilia o responsável pelo o mesmo, gerenciando seus produtos.",
    image: '/images/Nativo App.png',
    tags: ['Flutter'],
    source: 'https://drive.google.com/drive/folders/1buBDFlpBMApjzFXOEzP40mbeZvRlCIAv?usp=sharing',
    visit: 'https://github.com/JorgeHenrys',
    id: 6,
  },
  {
    title: 'Sos Serviços',
    description: "Uma aplicação Mobile que recebe o cadastro de pessoas que prestam algum tipo de serviço e pessoas que buscam por esses tipos de serviços.",
    image: '/images/Sos Servicos.png',
    tags: ['Flutter', 'Firebase'],
    source: 'https://drive.google.com/drive/folders/1ME59zPe8bQJlL-0yc5ifW-Yv0yLAbLpy?usp=sharing',
    visit: 'https://github.com/JorgeHenrys',
    id: 7,
  }
];

export const TimeLineData = [
  { year: 2018, text: 'Dei ínicio a minha jornada', },
  { year: 2019, text: 'Trabalhei para uma empresa de Sistemas Comerciais', },
  { year: 2020, text: 'Trabalhei como Freelancer', },
  { year: 2021, text: 'Embarquei no mundo do Game Dev e atualmente trabalho prestando serviço para uma Empresa Home Office', },
];